version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/create_main_subzone_query_log_kms/prereq"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/create_module_query_log_kms/prereq"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/create_main_zone_query_log_kms/prereq"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
